#pragma once

// From glfw3.h
#define SHARD_MOUSE_BUTTON_1 0
#define SHARD_MOUSE_BUTTON_2 1
#define SHARD_MOUSE_BUTTON_3 2
#define SHARD_MOUSE_BUTTON_4 3
#define SHARD_MOUSE_BUTTON_5 4
#define SHARD_MOUSE_BUTTON_6 5
#define SHARD_MOUSE_BUTTON_7 6
#define SHARD_MOUSE_BUTTON_8 7
#define SHARD_MOUSE_BUTTON_LAST SHARD_MOUSE_BUTTON_8
#define SHARD_MOUSE_BUTTON_LEFT SHARD_MOUSE_BUTTON_1
#define SHARD_MOUSE_BUTTON_RIGHT SHARD_MOUSE_BUTTON_2
#define SHARD_MOUSE_BUTTON_MIDDLE SHARD_MOUSE_BUTTON_3